#ifndef SHADER_BINDING_H
#define SHADER_BINDING_H

#define SHADOW_MAP_TEXTURE 6

#define GBUFFER_ALBEDO_TEXTURE 0
#define GBUFFER_NORMAL_TEXTURE 1
#define GBUFFER_DEPTH_TEXTURE 2

#define CAMERA_UNIFORM_BUFFER 0

#define VOXEL_ALBEDO_IMAGE 0
#define VOXEL_NORMAL_IMAGE 1
#define VOXEL_RADIANCE_IMAGE 2

#endif
