#ifndef SHADER_BINDING_H
#define SHADER_BINDING_H

#define CAMERA_UNIFORM_BUFFER 0

// at most 8 image units
#define MOTION_BLUR_TILE_0_IMAGE 0

#define VOXEL_RADIANCE_IMAGE 1
#define VOXEL_RADIANCE_MIPMAP_IMAGE 2

#define GBUFFER_ALBEDO_TEXTURE 0
#define GBUFFER_NORMAL_TEXTURE 1
#define GBUFFER_DEPTH_TEXTURE 2
#define GBUFFER_VELOCITY_TEXTURE 3

#define SHADOW_MAP_TEXTURE 4

#define TUMBLER_TEXTURE 5
#define FLOOR_TEXTURE 6

#define BLOOM_TEXTURE 7

#define LIGHT_TEXTURE 8
#define TAA_TEXTURE 9

#define MOTION_BLUR_TILE_0_TEXTURE 10
#define MOTION_BLUR_TILE_TEXTURE 11

#define VOXEL_RADIANCE_TEXTURE 12
#define VOXEL_RADIANCE_MIPMAP_TEXTURE 13

#endif
